apiVersion: v1
entries:
  vechr:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-12-10T19:28:21.542286298Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.18.3
    - condition: kong.enabled
      name: kong
      repository: https://charts.konghq.com
      version: 2.12.0
    description: Helm Chart for Vechr Kubernetes
    digest: 552297ed6952b27e5480628841665ac49b35bb3a7139afd1dface4752e07a510
    home: https://github.com/vechr
    icon: https://raw.githubusercontent.com/vechr/vechr-atlas/master/images/logo.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr
    type: application
    urls:
    - https://github.com/vechr/vechr-atlas/releases/download/vechr-1.0.4/vechr-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-12-10T15:40:20.843401744Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.18.3
    - condition: kong.enabled
      name: kong
      repository: https://charts.konghq.com
      version: 2.12.0
    description: Helm Chart for Vechr Kubernetes
    digest: d11b2c77227b47df5443553b7daeb43b4024110e6b033b2f8b06331935fabef1
    home: https://github.com/vechr
    icon: https://raw.githubusercontent.com/vechr/vechr-atlas/master/images/logo.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr
    type: application
    urls:
    - https://github.com/vechr/vechr-atlas/releases/download/vechr-1.0.3/vechr-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2022-12-10T13:46:05.581702261Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.18.3
    - condition: kong.enabled
      name: kong
      repository: https://charts.konghq.com
      version: 2.12.0
    description: Helm Chart for Vechr Kubernetes
    digest: 6f2d1e55b172ee211b8a4526a5ede927a84dd42680bd24c6a3acc71a336f11aa
    home: https://github.com/vechr
    icon: https://raw.githubusercontent.com/vechr/vechr-atlas/master/images/logo.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr
    type: application
    urls:
    - https://github.com/vechr/vechr-atlas/releases/download/vechr-1.0.2/vechr-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-12-09T03:52:05.770420121Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.18.3
    - condition: kong.enabled
      name: kong
      repository: https://charts.konghq.com
      version: 2.12.0
    description: Helm Chart for Vechr Kubernetes
    digest: 5ca22bd7ee7a0abf60f195d83cdfc9f323cf9ac289bc5f8cabe75e4138a3e9e4
    home: https://github.com/vechr
    icon: https://raw.githubusercontent.com/vechr/vechr-atlas/master/images/logo.svg
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr
    type: application
    urls:
    - https://github.com/vechr/vechr-atlas/releases/download/vechr-1.0.1/vechr-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-12-07T17:53:40.681354864Z"
    dependencies:
    - condition: nats.enabled
      name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.18.3
    - condition: kong.enabled
      name: kong
      repository: https://charts.konghq.com
      version: 2.12.0
    description: Helm Chart for Vechr Kubernetes
    digest: 94bfa5257b4959965e53e41b66b369652382e9132056e0977949366b5b377b54
    home: https://github.com/vechr
    keywords:
    - Vechr
    - IoT
    maintainers:
    - email: isnaen70@gmail.com
      name: zulfikar
      url: https://github.com/zulfikar4568
    name: vechr
    type: application
    urls:
    - https://github.com/vechr/vechr-atlas/releases/download/vechr-1.0.0/vechr-1.0.0.tgz
    version: 1.0.0
generated: "2022-12-10T19:28:21.542307198Z"
